apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-ns-dev
  namespace: ns-dev
spec:
  hard:
    pods: "10"
    requests.cpu: "500m"
    requests.memory: "512Mi"
    limits.cpu: "1"
    limits.memory: "1Gi"
