apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-ns-prod
  namespace: ns-prod
spec:
  hard:
    pods: "20"
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: "2Gi"
