apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-test
  namespace: ns-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: no-test
  template:
    metadata:
      labels:
        app: no-test
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            requests:
              cpu: "300m"
              memory: "300Mi"
            limits:
              cpu: "300m"
              memory: "300Mi"
          ports:
            - containerPort: 80
